export const equiposColombia = [
  'Águilas Doradas',
  'Alianza Petrolera',
  'América de Cali',
  'Atlético Bucaramanga',
  'Atlético Junior',
  'Atlético Nacional',
  'Cortuluá',
  'Deportes Tolima',
  'Deportivo Cali',
  'Deportivo Pasto',
  'Deportivo Pereira',
  'Envigado FC',
  'Independiente Medellín',
  'Independiente Santa Fe',
  'Jaguares de Córdoba',
  'La Equidad',
  'Millonarios',
  'Once Caldas',
  'Patriotas FC',
  'Unión Magdalena',
];
